name: Strapi Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (fix platform issue)
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build
        run: npm run build

      - name: Zip
        run: zip -r app.zip . -x ".git/*"

      - name: Azure login
        run: az login --identity --client-id 791e261e-8abe-4360-85bd-d6d5527c3760

      - name: Deploy
        run: |
          az webapp deploy \
            --resource-group Devops \
            --name strapiprelogin \
            --src-path app.zip \
            --type zip