name: Strapi Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: [self-hosted,Linux,X64]
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 20.x


            - name: Install dependencies
              run: npm install

            - name: Build Strapi application
              run: npm run build

            - name: Zip artifact
              run: zip -r app.zip . -x "node_modules/*" ".git/*"

            - name: Azure login
              run: |
                az login --identity --client-id 791e261e-8abe-4360-85bd-d6d5527c3760
            - name: Deploy to Azure Web App
              run: |
                az webapp deploy \
                    --resource-group Devops \
                    --name strapiprelogin \
                    --src-path app.zip \
                    --type zip \
                    --build-remote true